[build]
  base = "."
  command = "npm run build:all"
  publish = "client/build"
  functions = "server/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200 