[build]
  base = "server"
  command = "npm run netlify:build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200 